// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw0uEBwxxI4YWHN9koTvtuusu7RBfdvf0',
    appId: '1:1052430975911:web:9b4e3bb7d4492f69326c82',
    messagingSenderId: '1052430975911',
    projectId: 'do-som2thing-nomad2ndfinal',
    authDomain: 'do-som2thing-nomad2ndfinal.firebaseapp.com',
    storageBucket: 'do-som2thing-nomad2ndfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgq6ZXTrLZwxXMivqz-pe4wyl4cgLZoAY',
    appId: '1:1052430975911:android:6139996a1f44bfc9326c82',
    messagingSenderId: '1052430975911',
    projectId: 'do-som2thing-nomad2ndfinal',
    storageBucket: 'do-som2thing-nomad2ndfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5wmUFjY_XZK6e0jwgwpzWPacXGiD7SGc',
    appId: '1:1052430975911:ios:fe32b46677019d92326c82',
    messagingSenderId: '1052430975911',
    projectId: 'do-som2thing-nomad2ndfinal',
    storageBucket: 'do-som2thing-nomad2ndfinal.appspot.com',
    iosBundleId: 'com.example.nomadFlutter2ndFinal',
  );
}
